# Generated by Django 3.2.19 on 2023-06-21 22:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_remove_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
