# Generated by Django 3.2.19 on 2023-06-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_auto_20230621_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
