# Generated by Django 3.2.19 on 2023-06-24 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_auto_20230624_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dyoueyepq/image/upload/v1687522627/recipe-placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
