# Generated by Django 3.2.19 on 2023-06-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0013_auto_20230624_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True, max_length=80),
        ),
    ]
