# Generated by Django 3.2.19 on 2023-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0016_alter_recipe_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
